version: "3.7"

services:
  webserver:
    image: dodo037/webserver_image
    ports:
      - "8008:8008"
    depends_on:
      - database
    networks:
      - app-network

  database:
    image: dodo037/database_image
    ports:
      - "3306:3306"
    volumes:
      - ./DB/myDatabase.sql:/docker-entrypoint-initdb.d/myDatabase.sql
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=myDatabase
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_AUTHENTICATION_PLUGIN=mysql_native_password
    networks:
      - app-network

networks:
  app-network: