apiVersion: apps/v1
kind: Deployment
metadata:
  name: myserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myserver
  template:
    metadata:
      labels:
        app: myserver
    spec:
      containers:
      - name: myserver
        image: dodo037/webserver_image:latest
        ports:
        - containerPort: 8008
        env:
        - name: DB_HOST
          value: "mydatabase"
        - name: DB_USER
          value: "user"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "myDatabase"
---
apiVersion: v1
kind: Service
metadata:
  name: myserver
spec:
  selector:
    app: myserver
  ports:
    - protocol: TCP
      port: 8008
      targetPort: 8008
  type: LoadBalancer
